config/routes.rb
Rails.application.routes.draw do
  get 'global_users/refresh'
  resources :global_users
  resources :user_loads do
    collection { post :import}
  end
  # get 'global_user/edit'
  #
  # get 'global_user/update'
  #
  # get 'global_user/index'
  #
  # get 'global_user/destroy'

  devise_for :users
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'global_user#index'
  root 'global_users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  establish_connection "employee".to_sym
end

app/models/global_user.rb
class GlobalUser < ApplicationRecord
  self.table_name = "zz_users"
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = "zz_users"
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

end

app/models/user_load.rb
class UserLoad < ApplicationRecord
  establish_connection "development".to_sym
  def self.import(file)
    UserLoad.delete_all
    CSV.foreach(file.path, headers: true) do |row|
      UserLoad.create! row.to_hash
    end
  end

  def self.load_users
    User.delete_all
    all.each do |p|
      if !p.badge.blank? && !p.ssn4.blank?
        # good user data create a user
        u = User.new
        u.email = p.badge
        u.password = p.ssn4
        u.save
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/global_users_controller.rb
class GlobalUsersController < ApplicationController
  before_action :set_global_user, only: [:edit, :update, :destroy]

  # GET /global_users
  def index
    if user_signed_in? && current_user.master_user
      @global_users = GlobalUser.all
    else
      redirect_to signout_path and return
    end
  end

  # GET /global_users/1/edit
  def edit
  end

  # PATCH/PUT /global_users/1
  def update
    respond_to do |format|
      if @global_user.update(global_user_params)
        format.html { redirect_to global_users_url, notice: 'Global user was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /global_users/1
  def destroy
    @global_user.destroy
    respond_to do |format|
      format.html { redirect_to global_users_url, notice: 'Global user was successfully destroyed.' }
    end
  end

  # GET /global_users/refresh
  def refresh
    employees = Employee.all
    employees.each do |e|
      if e.Employee_Status == 'Active'
        # See if a User exists for this active employee. If not then create one if the ssn4 is present.
        u = User.find_by email: e.Badge_
        if u.blank? && !e.ssn4.blank?
          u = User.new
          u.email = e.Badge_
          u.password = e.ssn4
          u.take_in = true
          u.save
          logger.info 'user '+e.Badge_+' created'
        end
      elsif e.Employee_Status == 'Terminated'
        # See if a User exists for this terminated employee. If it does then delete it.
        u = User.find_by email: e.Badge_
        if !u.blank?
          u.delete
          logger.info 'user '+e.Badge_+' deleted'
        end
      end
    end
    redirect_to global_users_url, notice: 'Global users were successfully refreshed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_global_user
      @global_user = GlobalUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def global_user_params
      params.require(:global_user).permit(:manager, :manager_id, :user_dept, :dept_manager, :dispatch, :holiday_bird_caps, :master_user, :order_input, :pricing,
        :prospects, :rapid_order, :refusals, :short_term_trucks, :take_in, :temp_hire, :truck_monitoring, :hardware, :campaign_rep1, :campaign_rep2, :campaigns,
        :campaigns_admin, :cod, :cod_role, :campaign_role, :campaign_manager, :focus_items, :focus_items_rep1, :focus_items_rep2, :focus_items_role,
        :focus_items_manager, :retail_order_input, :retail_rapid_order, :retail_order_input_rep1, :retail_order_input_rep2, :retail_rapid_order_role,
        :complaints, :complaints_role, :complaints_dc)
    end
end

app/controllers/user_loads_controller.rb
class UserLoadsController < ApplicationController
  def import
    UserLoad.import(params[:file])
    redirect_to root_url, notice: "Users imported."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/global_user_helper.rb
module GlobalUserHelper
end

app/helpers/global_users_helper.rb
module GlobalUsersHelper
end

app/helpers/user_loads_helper.rb
module UserLoadsHelper
end

app/views/global_users/_form.html.erb
<%= form_with(model: global_user, local: true) do |form| %>
  <% if global_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(global_user.errors.count, "error") %> prohibited this global_user from being saved:</h2>

      <ul>
      <% global_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :prospects %> </th>
        <th> <%= form.label :manager_id %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :prospects, id: :global_user_prospects %> </td>
        <td> <%= form.text_field :manager_id, id: :global_user_manager_id %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :truck_monitoring %> </th>
        <th> <%= form.label :user_dept %> </th>
        <th> <%= form.label :dept_manager %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :truck_monitoring, id: :global_user_truck_monitoring %> </td>
        <td> <%= form.text_field :user_dept, id: :global_user_user_dept %> </td>
        <td> <%= form.text_field :dept_manager, id: :global_user_dept_manager %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :campaigns %> </th>
        <th> <%= form.label :campaigns_admin %> </th>
        <th> <%= form.label :campaign_rep1 %> </th>
        <th> <%= form.label :campaign_rep2 %> </th>
        <th> <%= form.label :campaign_role %> </th>
        <th> <%= form.label :campaign_manager %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :campaigns, id: :global_user_campaigns %> </td>
        <td> <%= form.check_box :campaigns_admin, id: :global_user_campaigns_admin %> </td>
        <td> <%= form.text_field :campaign_rep1, id: :global_user_campaign_rep1 %> </td>
        <td> <%= form.text_field :campaign_rep2, id: :global_user_campaign_rep2 %> </td>
        <td> <%= form.select :campaign_role, ['', 'Marketing', 'Food Service', 'Admin'], {}, {:value => params[:global_user_campaign_role]} %> </td>
        <td> <%= form.text_field :campaign_manager, id: :global_user_campaign_manager %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :cod, "COD" %> </th>
        <th> <%= form.label :cod_role, "COD role" %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :cod, id: :global_user_cod %> </td>
        <td> <%= form.select :cod_role, ['', 'Logistics', 'Accounting', 'Admin'], {}, {:value => params[:global_user_cod_role]} %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :complaints, "Complaints" %> </th>
        <th> <%= form.label :complaints_role, "Complaints role" %> </th>
        <th> <%= form.label :complaints_dc, "Complaints DC" %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :complaints, id: :global_user_complaints %> </td>
        <td> <%= form.select :complaints_role, ['', 'Accounting', 'Inventory', 'Logistics', 'Operations', 'Quality', 'Sales', 'Admin'], {}, {:value => params[:global_user_complaints_role]} %> </td>
        <td> <%= form.select :complaints_dc,  ['NJ', 'IL', 'GA', 'TX', 'CO'], {}, {:value => params[:global_user_complaints_dc]} %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :focus_items %> </th>
        <th> <%= form.label :focus_items_manager %> </th>
        <th> <%= form.label :focus_items_rep1 %> </th>
        <th> <%= form.label :focus_items_rep2 %> </th>
        <th> <%= form.label :focus_items_role %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :focus_items, id: :global_user_focus_items %> </td>
        <td> <%= form.text_field :focus_items_manager, id: :global_user_focus_items_manager %> </td>
        <td> <%= form.text_field :focus_items_rep1, id: :global_user_focus_items_rep1 %> </td>
        <td> <%= form.text_field :focus_items_rep2, id: :global_user_focus_items_rep2 %> </td>
        <td> <%= form.select :focus_items_role, ['Admin', 'Manager', 'Rep'], {}, {:value => params[:global_user_focus_items_role]} %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :retail_order_input %> </th>
        <th> <%= form.label :retail_order_input_rep1 %> </th>
        <th> <%= form.label :retail_order_input_rep2 %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :retail_order_input, id: :global_user_retail_order_input %> </td>
        <td> <%= form.text_field :retail_order_input_rep1, id: :global_user_retail_order_input_rep1 %> </td>
        <td> <%= form.text_field :retail_order_input_rep2, id: :global_user_retail_order_input_rep2 %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :retail_rapid_order %> </th>
        <th> <%= form.label :retail_rapid_order_role %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :retail_rapid_order, id: :global_user_retail_rapid_order %> </td>
        <td> <%= form.select :retail_rapid_order_role, ['Admin', 'Data entry'], {}, {:value => params[:global_user_retail_rapid_order_role]} %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :dispatch %> </th>
        <th> <%= form.label :hardware %> </th>
        <th> <%= form.label :holiday_bird_caps %> </th>
        <th> <%= form.label :order_input %> </th>
        <th> <%= form.label :pricing %> </th>
        <th> <%= form.label :rapid_order %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :dispatch, id: :global_user_dispatch %> </td>
        <td> <%= form.check_box :hardware, id: :global_user_hardware %> </td>
        <td> <%= form.check_box :holiday_bird_caps, id: :global_user_holiday_bird_caps %> </td>
        <td> <%= form.check_box :order_input, id: :global_user_order_input %> </td>
        <td> <%= form.check_box :pricing, id: :global_user_pricing %> </td>
        <td> <%= form.check_box :rapid_order, id: :global_user_rapid_order %> </td>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th> <%= form.label :refusals %> </th>
        <th> <%= form.label :short_term_trucks %> </th>
        <th> <%= form.label :take_in %> </th>
        <th> <%= form.label :temp_hire %> </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= form.check_box :retail_rapid_order, id: :global_user_retail_rapid_order %> </td>
        <td> <%= form.check_box :refusals, id: :global_user_refusals %> </td>
        <td> <%= form.check_box :short_term_trucks, id: :global_user_short_term_trucks %> </td>
        <td> <%= form.check_box :take_in, id: :global_user_take_in %> </td>
        <td> <%= form.check_box :temp_hire, id: :global_user_temp_hire %> </td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/global_users/edit.html.erb
<p id="notice"><%= notice %></p>
<h2>Edit User <%= @global_user.email %></h2>

<%= render 'form', global_user: @global_user %>

<br>
<%= link_to 'Back', global_users_path, class: "btn btn-primary" %>

app/views/global_users/index.html.erb
<p id="notice"><%= notice %></p>

<table id="normal_dt"  class="stripe" class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th>User</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @global_users.each do |global_user| %>
      <tr>
        <td>&nbsp;&nbsp;<%= global_user.email %></td>
        <td><%= link_to 'Edit', edit_global_user_path(global_user), class: "btn btn-primary" %></td>
        <td><%= link_to 'Delete', global_user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>      </tr>
    <% end %>
  </tbody>
</table>

<h2> Refresh Users</h2>
<%= link_to 'Refresh', global_users_refresh_path, class: "btn btn-primary" %>

app/views/layouts/_header.html.erb
<span class="primary-logo">
</span>
<span id="navbar">
  <% if user_signed_in? %>
    <span><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %></span>
  <% end %>
</span>
<h1 class="title">Global Users
</h1>
<% if user_signed_in? %>
  <span>Signed in as <%= current_user.email %></span>
<% else %>
  <span>No user currently signed in</span>
<% end %>
<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Global Users</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="position: fixed; top: 0px; width: 100%; height: 8em; background-color: white; z-index: 100;">
      <%= render 'layouts/header' %>
    </div>
    <div style="margin-top: 8.5em;">
      <%= yield %>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script src="/assets/printPreview.js"></script>
    <script src="/assets/myjavascript.js"></script>
  </body>
</html>